name       : perl-xml-sax
version    : 1.0
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-SAX-1.00.tar.gz : 45ea6564ef8692155d57b2de0862b6442d3c7e29f4a9bc9ede5d7ecdc74c2ae3
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : XML::SAX framework classes for Perl SAX2 XML parsers, filters, and drivers.
description: |
    XML::SAX consists of several framework classes for using and building
    Perl SAX2 XML parsers, filters, and drivers.
builddeps  :
    - perl-xml-namespacesupport
    - perl-xml-saxbase
rundeps    :
    - perl-xml-namespacesupport
    - perl-xml-saxbase
setup      : |
    %patch -p1 < $pkgfiles/write-no-ParserDetails.ini.patch
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
