name       : perl-xml-sax
version    : '1.02'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-SAX-1.02.tar.gz : 4506c387043aa6a77b455f00f57409f3720aa7e553495ab2535263b4ed1ea12a
homepage   : https://metacpan.org/pod/XML::SAX
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : XML::SAX - Simple API for XML
description: |
    XML::SAX is a SAX parser access API for Perl. It includes classes and APIs required for implementing SAX drivers, along with a factory class for returning any SAX parser installed on the user's system.
builddeps  :
    - perl-xml-namespacesupport
    - perl-xml-saxbase
rundeps    :
    - perl-xml-namespacesupport
    - perl-xml-saxbase
setup      : |
    %patch -p1 < $pkgfiles/write-no-ParserDetails.ini.patch
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
